name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      working-directory: build
      run: ctest --output-on-failure -C Release

    - name: Create Release and Upload Asset
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # Extract version from tag (e.g., v1.0.1 -> 1.0.1)
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Create release
        gh release create "v${VERSION}" \
          --title "Release ${VERSION}" \
          --generate-notes \
          build/http_server